### PR TITLE
missing MANIFEST.in added

### PR DESCRIPTION
**Pull request by hootnot**
This will get requirements.txt and LICENSE packaged  and fix the error

Nice images ...
No thanks! Your welcome!

### CODE REVIEW

**Comment by itamarhaber** [comment]
Thanks. Does it make sense in your opinion to have non-tagged builds after_success deployed to pypitest and then pulled in the CI?

**Comment by hootnot** [comment]
.. see what you mean. In that case you would have detected the failure you had due to the missing MANIFEST.in
We could have known it if we deployed from a locally built package by just giving: **python setup.py sdist bdist_wheel** and then **pip install ...* that.
Once such a package setup is made it stays pretty static.

So to come back to your question: I would not do it personally, but it is an interesting thought to detect such an error.
Wouldn't it be enough to just build the package  and install it during the CI run *after_success* ?
I will keep the thought, but running a local build it the priotity I guess. If saves a faulty build. But needs some discipline.
I found myself in the same kind of issues related to Python 2.x / 3.x, running a local testrun an find no errors, push it and then find out that there are errors for the Python version not ran the tests for.

**Comment by itamarhaber** [comment]
> We could have known it if we deployed from a locally built package...

You may have known, I'm very fresh on these matters ;) I agree that once done, the collateral should remain immutable, but given that this is a framework it could be a way to catch errors in a fool-proof (read Itamar-proof) manner.

> Wouldn't it be enough to just build the package and install it during the CI run after_success?

IIUC this would post-deploying it to the real wheel and then it would be too late and breakage becomes public, no?

> We could have known it if we deployed from a locally built package by just giving: python setup.py sdist bdist_wheel and then *pip install ... that.
+
> but running a local build it the priotity I guess.

Okay, but following the framework logic and unless testpypi is used, this should be included somewhere as a reminder at the very least... e.g. in the tip provided by `setup.py publish` perhaps.

Anyway, just a thought and most probably over-optimizing it

**Comment by hootnot** [comment]
Maybe you should take a look at: https://docs.travis-ci.com/user/deployment/pypi/ it gives various possibilities regarding deployment. I also see a **before_deploy**.

I use this **deploy** attribute myself in a number of packages as I wrote earlier. But I have no experience with the fancy stuf on the URL.

**Pull request merged**
