### PR TITLE
Test suite

### PR DESCRIPTION
**Pull request by hootnot**
- [x] testsuite added in the distutils standard way
- [x] setup.py modified a lot : 
    - will retrieve the version from __init__ instead hardcoded to make versioning easier
    - will fetch requirements from *requirements.txt*, no errors from double admin.
    - **setup.py publish** gives you the **git** command to tag the last version : configure .travis.yml with a deploy *attribute* and it will enable you to deploy to pypi from Travis using twine
- [x] added pyth 3.3 / 3.4 and 3.6 : also passing
- [x] version badge added (right versions will show up after merging)
- [ ] implement coverage ? (it's easy to hook up coveralls) (and landscape / codacy)

Personally I deploy to pypi from Travis: bump the version in \_\_init\_\_, update your master, tag it and you are done.

- [x] rewrite README.md to README.rst : reason I rewrote my README.md's to README.rst's is because pypi likes .rst files a lot better. If you have a README.rst and modify the setup.py for that, then the deployment to pypi will show the README there also.

This setup is partially based on work of Tom Christie, @tomchristie, author of the Django Rest Framework, he wrote an article about depoying to pypi: https://tom-christie.github.io/articles/pypi/. For some of my own packages I've extended that a lot.

Travis has some annoying differences between the different environments. Sometimes you run into them

### CODE REVIEW

**Comment by itamarhaber** [comment]
@hootnot waiting for the fat lady to sing, but this looks great!

**Comment by hootnot** [comment]
do you want me to fix README from md to rst ?

**Comment by tomchristie** [comment]
That'd be @tom-christie.

**Comment by itamarhaber** [comment]
rst makes more sense given your argument and experience, thanks for that too. I'll merge as is unless you plan to add coverage (yes please!).

**Comment by hootnot** [comment]
Fixed the setEncoder/setDecoder internal links. Should be it now.

You can merge now if you like.

To setup coverage you need to modify .travis.yml with a key from coveralls.io . You are the boss! so you have to do this because of key related stuf. 

Lets handle this one first

**Comment by itamarhaber** [comment]
Thanks again -merging and starting to think about releasing the next version codenamed "hootnot" :)

**Comment by hootnot** [comment]
... I would be honoured :-), saw the 95% coverage too. A few extra tests and you have it 100%.

The version still sits on 2.7, that  is because that info is retrieve from pypi and not from the master as I wrote in the PR. So when you upload a new release that is fixed.

**Comment by itamarhaber** [comment]
In case I forgot to say it, thank you. After taking the project for a test drive, it feels like I moved from



to



Getting this atm, but I'm sure it is something that I missed:

```bash
$ pip install rejson
Collecting rejson
  Downloading rejson-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-EobKFa/rejson/setup.py", line 22, in <module>
        requirements = map(str.strip, open("requirements.txt").readlines())
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-EobKFa/rejson/
```

**Pull request merged**
